# Generated by Django 2.1.7 on 2019-04-24 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('wh_id', models.CharField(max_length=30)),
                ('wh_addr_x', models.CharField(max_length=30)),
                ('wh_addr_y', models.CharField(max_length=30)),
                ('dest_x', models.CharField(max_length=30)),
                ('dest_y', models.CharField(max_length=30)),
                ('cur_status', models.CharField(choices=[('p', 'wait for pick up'), ('o', 'out for delivery'), ('d', 'delivered')], max_length=30)),
                ('ready_for_pickup_time', models.CharField(max_length=30)),
                ('load_time', models.CharField(blank=True, max_length=30, null=True)),
                ('delivered_time', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('cur_status', models.CharField(choices=[('i', 'IDLE'), ('t', 'TRAVELING'), ('l', 'LOADING'), ('d', 'DELIVERING')], max_length=30)),
                ('pos_x', models.CharField(max_length=30)),
                ('pos_y', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('world_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('curr', models.BooleanField(default=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='world',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='myUPS.World'),
        ),
        migrations.AddField(
            model_name='package',
            name='truck',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='myUPS.Truck'),
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='myUPS.Account'),
        ),
        migrations.AddField(
            model_name='package',
            name='world',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='myUPS.World'),
        ),
        migrations.AddField(
            model_name='account',
            name='world',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='myUPS.World'),
        ),
    ]
